### ISSUE TITLE
Connection Features should also wiork with HTTPS and/or Authentication

### ISSUE THREAD

**Issue by Apollon77** [smiling-Jack/ioBroker.scriptgui#4]
I have configured my ccu.io so that I can reach a https+authentication version using a port-forwarding also from the Internet. But the ScriptGUI.app don't want to connect as soon as HTTPS/Auth is present (without providing an error.message, but blue flag only appears very short).

More verbose error messages on connection errors would be great too :-)

**Comment by smiling-Jack** [comment]
In der neuen Browser variante nicht nötig
